Vagrant.configure("2") do |config|
    config.vm.provision :shell, path: "bootstrap.sh"
    config.vm.box = "ubuntu/bionic64"
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
    end
    config.vm.define "varnish1" , autostart: true do |varnish1|
        varnish1.vm.network "private_network", ip: "192.168.33.60"
        varnish1.vm.network "forwarded_port", guest: 6081, host: 6081
        varnish1.vm.network "forwarded_port", guest: 6082, host: 6082
    end

    config.vm.define "varnish2" , autostart: true do |varnish2|
        varnish2.vm.network "private_network", ip: "192.168.33.70"
        varnish2.vm.network "forwarded_port", guest: 6081, host: 6083
        varnish2.vm.network "forwarded_port", guest: 6082, host: 6084
    end
    #config.vm.define "dbproxy1" , autostart: true do |dbproxy1|
    #    dbproxy1.vm.network "private_network", ip: "192.168.33.80"
    #end
  end