Vagrant.configure("2") do |config|
    config.vm.provision :shell, path: "bootstrap.sh"
    
    config.vm.box = "ubuntu/bionic64"
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
    end
    config.vm.define "db1" , autostart: true do |db1|
        db1.vm.network "private_network", ip: "192.168.33.50"
        db1.vm.network "forwarded_port", guest: 3306, host: 33061

    end

    config.vm.define "db2" , autostart: true do |db2|
        db2.vm.network "private_network", ip: "192.168.33.51"
        db2.vm.network "forwarded_port", guest: 3306, host: 33062
    end
    config.vm.define "db3" , autostart: true do |db3|
        db3.vm.network "private_network", ip: "192.168.33.52"
        db3.vm.network "forwarded_port", guest: 3306, host: 33063
    end
  end