Vagrant.configure("2") do |config|
    config.vm.provision :shell, path: "bootstrap.sh"
    config.vm.box = "ubuntu/bionic64"
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
    end
    config.vm.define "web1" , autostart: true do |web1|
        web1.vm.network "private_network", ip: "192.168.33.10"
        web1.vm.network "forwarded_port", guest: 8080, host: 8081
    end

    config.vm.define "web2" , autostart: true do |web2|
        web2.vm.network "private_network", ip: "192.168.33.11"
        web2.vm.network "forwarded_port", guest: 8080, host: 8082
    end
    config.vm.define "web3" , autostart: true do |web3|
        web3.vm.network "private_network", ip: "192.168.33.12"
        web3.vm.network "forwarded_port", guest: 8080, host: 8083
    end
  end