Vagrant.configure("2") do |config|
    config.vm.provision "shell", inline: "echo Hello"
    config.vm.box = "ubuntu/bionic64"
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
    end
    config.vm.define "jenkins" , autostart: true do |jenkins|
        jenkins.vm.network "private_network", ip: "192.168.33.30"
        config.vm.network "public_network", ip: "216.244.86.163"

    end

     config.vm.define "gitlab" , autostart: true do |gitlab|
         gitlab.vm.network "private_network", ip: "192.168.33.40"
         gitlab.vm.network "forwarded_port", guest: 80, host: 88
     end
  end
